---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  SPOTIFY_CLIENT_ID: create_spotify_client_id
  SPOTIFY_CLIENT_SECRET: create_spotify_client_secret
  GENIUS_CLIENT_ACCESS_TOKEN: create_genius_client_access_token
  GEMINI_API_KEY: create_gemini_api_key
  API_HOST: http://localhost:9292

test:
  DB_FILENAME: db/local/test.db
  SPOTIFY_CLIENT_ID: create_spotify_client_id
  SPOTIFY_CLIENT_SECRET: create_spotify_client_secret
  GENIUS_CLIENT_ACCESS_TOKEN: create_genius_client_access_token
  GEMINI_API_KEY: create_gemini_api_key
  API_HOST: http://localhost:9292

production:
  SPOTIFY_CLIENT_ID: create_spotify_client_id
  SPOTIFY_CLIENT_SECRET: create_spotify_client_secret
  GENIUS_CLIENT_ACCESS_TOKEN: create_genius_client_access_token
